swagger: '2.0'
info:
  title: Automatized Fisher Brand Shaker API
  version: "0.1"
  description: API to execute operations on shaker
consumes:
  - application/json
produces:
  - application/json
paths:
  /status:
    get:
      tags: [status]
      operationId: shaker.status
      summary: Queries for status
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached

  /is_ready:
    get:
      tags: [is_ready]
      operationId: shaker.is_ready
      summary: Queries for ready status
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached
  /start:
    get:
      tags: [start]
      operationId: shaker.start
      summary: Starts shaker
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached

  /stop:
    get:
      tags: [stop]
      operationId: shaker.stop
      summary: Stops shaker
      responses:
        200:
          description: Return response
          schema:
            $ref: '#/definitions/RobotResponse'
        404:
          description: Some kind of error, verbose output should be attached


# no parameters for shaker
# parameters:

definitions:
  RobotResponse:
    type: object
    required:
      - message
      - details
    properties:
      message:
        type: string
        description: The response as a short text
        example: "OK"
        minLength: 1
      details:
        type: string
        description: Complete backend stdoutput/stderror from command
        example: "Stack-trace...:"
        readOnly: true